#!/usr/bin/env bash
# set -x

[[ ! -f "arg_parse.sh" ]] && {
    echo "arg_parse.sh is missing! Critical dependency! Exiting..." >&2
    exit 255
}

source arg_parse.sh

[[ ! -d "targets/" ]] && {
    echo "no target directory! Nothing to run! Exiting..." >&2
    exit 255
}

[[ ! -f "targets/common.bash" ]] && {
    echo "Missing common target! Critical dependency! Exiting..." >&2
    exit 255
}

source targets/common.bash

[[ ! -d "modes/" ]] && {
    echo "Modes folder missing! Critical dependency! Exiting..." >&2
    exit 255
}

function init () {
    source .env
    export DOCKER_BUILDKIT=1
}

function cleanup () {
    [[ ${created_container} -eq 1 && ${persist} -eq 0 ]] && docker rm -v ${container_id} 2>&1 >/dev/null
}

function validate_dependencies () {

    return

}

# ================================================================================================
#                                               MAIN
function main () {
    validate_dependencies
    init
    validate_flags
    execute_flags
    validate_target
    cleanup
}

main

