
../.env
../.git/
../.github/
../.direnv/
../.editorconfig
../.gitignore
../tmp/
../build.tina
../dhelper
../flake.nix
../flake.lock
../highlight.css

../tina/
../deps/build/tina/dl.tar
../deps/build/tina/prebuilt.tar.gz
../deps/build/tina/gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabi.tar.xz
../deps/build/tina/riscv64-linux-x86_64-20200528.tar.xz
../deps/build/tina/go1.20.5.linux-amd64.tar.gz

../deps/rootfs/ffmpeg-2.7.6.tar.xz

../out/
../mnt/

../modes/
../targets/