
../.env
../.git/
../tmp/
../.editorconfig
../.gitignore
../build.tina
../dhelper
../flake.nix
../flake.lock
../highlight.css

../tina/.git/

../deps/rootfs/ffmpeg-2.7.6.tar.xz

../out/
../mnt/

../modes/
../targets/
